version: 0.0
os: linux
files:
- source: /dentonpolice
  destination: /srv/dentonpolice/dentonpolice
- source: /requirements.txt
  destination: /srv/dentonpolice/
- source: /config.yaml
  destination: /srv/dentonpolice/
- source: /Procfile
  destination: /srv/dentonpolice/
- source: /deploy/svlogd/config
  destination: /var/log/arrestinfo/crawler-1
hooks:
  BeforeInstall:
  - location: deploy/before_install.sh
    timeout: 180
  AfterInstall:
  - location: deploy/after_install.sh
    timeout: 60
  ApplicationStart:
  - location: deploy/application_start.sh
    timeout: 60
  ApplicationStop:
  - location: deploy/application_stop.sh
    timeout: 60
