# Default configuration values are defined here.
# Put values in a `config-env.yaml` file to override these defaults.

# Minimum number of seconds since getting the last report. Useful for
#   throttling automatic restarts from process supervisors.
minimum_report_age_s: 240

# Maximum number of seconds before raising a TimeoutError. (GH-16)
timeout:
  # When retrieving the HTML report. Normally finishes within 30 seconds.
  open_jail_report: 300
  # When opening the mugshot URL. Normally finishes within 30 seconds.
  open_one_mug_shot: 300

path:
  inmate_log: dentonpolice_log.json
  most_inmate_count: dentonpolice_most.txt
  mug_shot_dir: mugs
  recent_inmate_log: dentonpolice_recent.json
  recent_report_html: dentonpolice_recent.html

# Proxy setup
# If Polipo isn't running, you might need to start it manually after Tor.
proxy:
  host: 127.0.0.1
  # Be sure to use whatever port it is listening on (such as 8123).
  # The default port for Polipo used in the Tor Vidalia Bundle is 8118.
  port: 8123

# Twitter account info.
# Used to post most number of inmates in jail at once information.
twitter:
  enabled: false
  api_key: api_key_from_application_settings
  api_secret: api_secret_from_application_settings
  access_token: access_token_from_your_access_token
  access_token_secret: access_token_secret_from_your_access_token

# If the `aws` key exists, then the jail report will be saved to S3.
# aws:
#   s3:
#     region: some_region
#     bucket: some_bucket

# If the `sentry` key exists, error reporting via Sentry will be used.
# sentry:
#   dsn: some_dsn_for_your_project
